// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingSystem.Infrastructure.Data;

#nullable disable

namespace ParkingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    partial class ParkingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ParkingSystem.Core.Entities.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOccupied = false,
                            Number = "A01",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            IsOccupied = false,
                            Number = "A02",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            IsOccupied = false,
                            Number = "A03",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            IsOccupied = false,
                            Number = "A04",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            IsOccupied = false,
                            Number = "A05",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            IsOccupied = false,
                            Number = "A06",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            IsOccupied = false,
                            Number = "A07",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            IsOccupied = false,
                            Number = "A08",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            IsOccupied = false,
                            Number = "A09",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            IsOccupied = false,
                            Number = "A10",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            IsOccupied = false,
                            Number = "A11",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            IsOccupied = false,
                            Number = "A12",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            IsOccupied = false,
                            Number = "A13",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            IsOccupied = false,
                            Number = "A14",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            IsOccupied = false,
                            Number = "A15",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            IsOccupied = false,
                            Number = "A16",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            IsOccupied = false,
                            Number = "A17",
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            IsOccupied = false,
                            Number = "A18",
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            IsOccupied = false,
                            Number = "A19",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            IsOccupied = false,
                            Number = "A20",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            IsOccupied = false,
                            Number = "A21",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            IsOccupied = false,
                            Number = "A22",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            IsOccupied = false,
                            Number = "A23",
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            IsOccupied = false,
                            Number = "A24",
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            IsOccupied = false,
                            Number = "A25",
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            IsOccupied = false,
                            Number = "A26",
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            IsOccupied = false,
                            Number = "A27",
                            Type = 1
                        },
                        new
                        {
                            Id = 28,
                            IsOccupied = false,
                            Number = "A28",
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            IsOccupied = false,
                            Number = "A29",
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            IsOccupied = false,
                            Number = "A30",
                            Type = 1
                        },
                        new
                        {
                            Id = 31,
                            IsOccupied = false,
                            Number = "A31",
                            Type = 1
                        },
                        new
                        {
                            Id = 32,
                            IsOccupied = false,
                            Number = "A32",
                            Type = 1
                        },
                        new
                        {
                            Id = 33,
                            IsOccupied = false,
                            Number = "A33",
                            Type = 1
                        },
                        new
                        {
                            Id = 34,
                            IsOccupied = false,
                            Number = "A34",
                            Type = 1
                        },
                        new
                        {
                            Id = 35,
                            IsOccupied = false,
                            Number = "A35",
                            Type = 1
                        },
                        new
                        {
                            Id = 36,
                            IsOccupied = false,
                            Number = "A36",
                            Type = 1
                        },
                        new
                        {
                            Id = 37,
                            IsOccupied = false,
                            Number = "A37",
                            Type = 1
                        },
                        new
                        {
                            Id = 38,
                            IsOccupied = false,
                            Number = "A38",
                            Type = 1
                        },
                        new
                        {
                            Id = 39,
                            IsOccupied = false,
                            Number = "A39",
                            Type = 1
                        },
                        new
                        {
                            Id = 40,
                            IsOccupied = false,
                            Number = "A40",
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            IsOccupied = false,
                            Number = "A41",
                            Type = 2
                        },
                        new
                        {
                            Id = 42,
                            IsOccupied = false,
                            Number = "A42",
                            Type = 2
                        },
                        new
                        {
                            Id = 43,
                            IsOccupied = false,
                            Number = "A43",
                            Type = 2
                        },
                        new
                        {
                            Id = 44,
                            IsOccupied = false,
                            Number = "A44",
                            Type = 2
                        },
                        new
                        {
                            Id = 45,
                            IsOccupied = false,
                            Number = "A45",
                            Type = 2
                        },
                        new
                        {
                            Id = 46,
                            IsOccupied = false,
                            Number = "A46",
                            Type = 3
                        },
                        new
                        {
                            Id = 47,
                            IsOccupied = false,
                            Number = "A47",
                            Type = 3
                        },
                        new
                        {
                            Id = 48,
                            IsOccupied = false,
                            Number = "A48",
                            Type = 4
                        },
                        new
                        {
                            Id = 49,
                            IsOccupied = false,
                            Number = "A49",
                            Type = 4
                        },
                        new
                        {
                            Id = 50,
                            IsOccupied = false,
                            Number = "A50",
                            Type = 4
                        });
                });

            modelBuilder.Entity("ParkingSystem.Core.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsParked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkingSpotId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate");

                    b.HasIndex("ParkingSpotId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ParkingSystem.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("ParkingSystem.Core.Entities.ParkingSpot", "ParkingSpot")
                        .WithMany("VehicleHistory")
                        .HasForeignKey("ParkingSpotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingSpot");
                });

            modelBuilder.Entity("ParkingSystem.Core.Entities.ParkingSpot", b =>
                {
                    b.Navigation("VehicleHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
